### ISSUE TITLE
Override location of project environments

### ISSUE THREAD

**Issue by mcg1969** [conda-incubator/conda-project#121]
anaconda-project offers the environment variable `ANACONDA_PROJECT_ENVS_PATH` as a means to override the location where environments are created. By default of course they go in `./envs/<name>`, but we may have reason to home the environments outside of the project itself.

This variable actually accepts a _comma-separated list_ of values. New environments are created in the first writable directory on the path.

You can see how anaconda-project does this here:
https://github.com/Anaconda-Platform/anaconda-project/blob/master/anaconda_project/env_spec.py#L318-L348

More information here: https://anaconda-project.readthedocs.io/en/latest/config.html

**Comment by AlbertDeFusco** [comment]
PR #159 adds support to change the location of `envs`
