### ISSUE TITLE
Use relative paths for the `sources:` field

### ISSUE THREAD

**Issue by mcg1969** [conda-incubator/conda-project#124]
The `sources:` section of the lock files should use paths that are relative to the project, otherwise the project bundle is not relocatable. Here's what I'm seeing:
```
(cp) m1mbp:testproj mgrant$ pwd
/Users/mgrant/Repos/conda-project/testproj
(cp) m1mbp:testproj mgrant$ conda project init
Locking dependencies for environment default on platforms osx-64, linux-64, win-64, osx-arm64: done
Project created at /Users/mgrant/Repos/conda-project/testproj
(cp) m1mbp:testproj mgrant$ grep sources -A 1 conda-lock.default.yml 
  sources:
  - /Users/mgrant/Repos/conda-project/testproj/environment.yml
```
I think this would be superior:
```
(cp) m1mbp:testproj mgrant$ grep sources -A 1 conda-lock.default.yml 
  sources:
  - ./environment.yml
```

**Comment by mcg1969** [comment]
Not sure whether this should be counted as a bug or an enhancement, but I'd lean towards bug.

**Comment by mattkram** [comment]
I agree with you. This was originally the behavior in `conda-lock`, and they changed to absolute paths. Last I checked they were going to put back the option for relative paths. I will dig up the relevant issues.

**Comment by mattkram** [comment]
Here is the issue I was thinking of: https://github.com/conda/conda-lock/issues/229

I haven't had time to catch up on what happened since the last time I read the thread.

**Comment by mcg1969** [comment]
It's frankly disappointing the change was subject to so little review: https://github.com/conda/conda-lock/pull/189

**Comment by mcg1969** [comment]
This might have corrected things: https://github.com/conda/conda-lock/pull/328

**Comment by mattkram** [comment]
It's actually been a problem for us internally, since different developers who re-run conda-lock inadvertently commit lots of changes to the lockfiles (we started using in some microservices and want to migrate in that direction).

**Comment by mattkram** [comment]
> This might have corrected things: https://github.com/conda/conda-lock/pull/328

That's good to know. I will check Monday. Last time I read up on it it was going to be merged and released, but hadn't been released yet. Admittedly that was a couple months ago.

**Comment by mcg1969** [comment]
Ewww, it's even worse with conda-lock 2.1.0:
```
  sources:
  - ../../../../../../../Users/mgrant/Repos/conda-project/testproj/environment.yml
```

**Comment by mcg1969** [comment]
The reason this is so ugly is that we are writing the lockfile in a temporary location, so the relative path between the lock file and the environments is off

**Comment by mattkram** [comment]
> Ewww, it's even worse with conda-lock 2.1.0:
> ```
>   sources:
>   - ../../../../../../../Users/mgrant/Repos/conda-project/testproj/environment.yml
> ```

That needs a `Path(p).relative_to(Path(__file__))` or something.

**Comment by mattkram** [comment]
> The reason this is so ugly is that we are writing the lockfile in a temporary location, so the relative path between the lock file and the environments is off

Ahhh. Interesting.
