### ISSUE TITLE
Add .gitignore to the created environment

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#25]
See https://github.com/python/cpython/issues/83417.

There is a general need for something like `.projectignore` and `.gitignore` within conda-project. By automatically adding a `.gitignore` to the installed envs we can be really certain they won't get checked in to a repo even if the project-level .gitignore is removed

**Comment by mattkram** [comment]
I just ran into this while testing against #22. The primary thing there is I would like a `.gitignore` with `envs/` in it, at least if I am using `git`. I'm not sure what the best approach would be here, since presumably some users may:

* Not use `git`
* Have a `git` repo already (and potentially a `.gitignore`, which we should add to but not wipe out)
* Need a template `.gitignore` to be created

**Comment by AlbertDeFusco** [comment]
Yes, there is a need to implement a project-level .gitignore file. We'll also need it (or another ignore file is not using git) for generating archives or container images.

In #22 the `prepare` command should create a .gitignore file at `./envs/<env-name)/.gitignore`. Did that happen for you or did it not work as expected? Perhaps I misunderstood the behavior or that's just not a good idea.

**Comment by mattkram** [comment]
`prepare` does appear to create a `.gitignore` in the environment, but I don't believe `git` respects that. I have never seen a `.gitignore` file that is not in the project root next to the `.git` directory.

The image below shows the staged files after the following steps:

* conda project create
* conda project prepare
* git init
* git add -A

<img width="608" alt="image" src="https://user-images.githubusercontent.com/11037737/187044214-95d6055d-f6f2-46de-8c14-c2c1e4776e69.png">

**Comment by mattkram** [comment]
Follow up: If instead, I add another step before `git add -A` to create the `.gitignore` via `echo "/envs/" >> .gitignore`, then I get the desired behavior:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/11037737/187044432-9a6a48cf-f552-4aa0-a052-c7c4d414c224.png">

**Comment by AlbertDeFusco** [comment]
Oh, I forgot to add `*` to the `./envs/<env-name>/.gitignore` file. I'll make a fix and we can contiue to discuss a project-level ignore file

**Comment by mattkram** [comment]
I did not know that works. Cool!

**Comment by AlbertDeFusco** [comment]
For inspiration npm has its own ingore file for operations like `pack`. If the .nmpignore is not present it will fall back to .gitignore

https://docs.npmjs.com/cli/v8/using-npm/developers#keeping-files-out-of-your-package

Anaconda-project has nearly identical behavior

https://anaconda-project.readthedocs.io/en/latest/user-guide/tasks/create-project-archive.html?highlight=.projectignore#excluding-files-from-the-archive

Does this approach make sense? I'm in favor of adding/merging a .gitignore file if not present in the project directory when a command is run (prepare, lock, etc.)
