### ISSUE TITLE
Prepare vs. Install

### ISSUE THREAD

**Issue by mattkram** [conda-incubator/conda-project#43]
anaconda-project uses the subcommand `prepare` to represent the action that installs all dependencies into an environment (or environments). Other environment management tools such as poetry and pipenv use the verb `install`.

Personally, I find `install` to be more intuitive.  I.e.:

- `conda project lock`
- `conda project install`

I'm opening this issue to discuss renaming this subcommand with an optional alias and potential deprecation path.

I propose to:

- rename `prepare` to `install`
- optionally alias `prepare` to invoke `install`
- optionally define a deprecation path to emit a warning and eventually deprecate the `prepare` terminology 

Thoughts?

**Comment by jbednar** [comment]
Calling it `install` seems clearer to me. My vote for my own person convenience would be to accept `prepare` as a synonym for `install` but print a warning that the real name of it is `install`. I will almost certainly type `conda project prepare` without ever really thinking about out, after all my history with `anaconda-project`!

**Comment by bkreider** [comment]
It looks like prepare in AP used to do a lot more things: https://github.com/Anaconda-Platform/anaconda-project/commit/bc1d872b77fb318943e521f3556bce0c0da39d57
