### ISSUE TITLE
[ENH] local condarc

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#5]
Conda does not currently read configuration settings from a `.condarc` file in your local directory, but it can be implemented in conda-project using the $CONDARC and setting it to the project directory for all conda commands 

https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc

**Comment by jbednar** [comment]
And pinning down the values of condarc options can be very important for making reproducible projects.

**Comment by AlbertDeFusco** [comment]
PR #9 added support for a local `.condarc` file.
