### ISSUE TITLE
Change naming convention for lockfiles

### ISSUE THREAD

**Issue by mattkram** [conda-incubator/conda-project#57]
Currently, we generate lockfiles with `conda-lock` with the following format: `{env_name}.conda-lock.yml`. However, this has the downside that the files are not sorted consecutively.

Instead, we should use the format `conda-lock.{env_name}.yml` so it is clear what these files are for, and they appear consecutively in the file browser.

**Comment by AlbertDeFusco** [comment]
Works for me
