### ISSUE TITLE
Drop Python 3.7 testing

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#66]
Given that there are some testing errors due to changes in MagicMock between Python 3.7 and 3.8 in #38 and that NumPy no longer provides Python 3.7 support it may be beneficial for conda-project to discontinue testing against it.

**Comment by mattkram** [comment]
I agree. I think we should modernize our support versions for Python & conda too. And update the test matrix accordingly.

**Comment by AlbertDeFusco** [comment]
Will do. I've determined that `experimental_solver` was deprecated in Conda 22.11 in favor of `solver` so I'll take special care of that in the libmamba tests when I add Conda versions to the test matrix
