### ISSUE TITLE
Subprocess or Conda API?

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#7]
Tools like [conda-lock](https://github.com/conda-incubator/conda-lock) and [anaconda-project](https://github.com/Anaconda-Platform/anaconda-project) _require_ Conda but do not _depend_ on Conda in their dependencies. They also integrate with Conda through subprocess calls.

Is there a disadvantage to using the [Conda Python API](https://docs.conda.io/projects/conda/en/latest/api/index.html) and adding Conda a dependency in the meta.yaml?

**Comment by mariusvniekerk** [comment]
In fact conda-lock even now vendors conda but will subprocess out to do a solve.

**Comment by mariusvniekerk** [comment]
Conda also does behave somewhat oddly in non-root environments. Things like where conda environments are created when in a nested env etc.

**Comment by AlbertDeFusco** [comment]
Thanks. I consider if vendoring conda provides us any value here.
