### ISSUE TITLE
Command and variable spec without local environment

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#79]
> I want to write a spec for conda-run to define commands and variables, but I don't want the env management and locking features, I will just use the global conda envs to execute this

**Comment by jlstevens** [comment]
The only thing I would add is that this would be nice as an *option* but not a default option. IMHO the namespace of selectable environments should be the ones in the project yaml spec by default (using `--environment`) but having to option to use `--global-environment` (or similar) would be nice as an escape hatch (a feature to be used when appropriate, not necessarily best practice).
